name: build
on:
  push:
jobs:
  xgo:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.15.x
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build with xgo
      uses: crazy-max/ghaction-xgo@v1
      with:
        xgo_version: latest
        go_version: ${{ matrix.go_version }}
        dest: build
        targets: windows/amd64,linux/amd64,darwin/amd64
        v: true
        x: true
        ldflags: -s -w
    - name: Build
      run: make all
